@startuml

class Usuario {
    - nombre: String
    - email: String
}

class Observacion {
    - fecha: Date
    - cantidadIndividuos: int
}

class Especie {
    - nombreComun: String
    - nombreCientifico: String
}

class Lugar {
    - nombre: String
    - latitud: double
    - longitud: double
}

class Fotografia {
    - archivo: String
}

Usuario "1" -- "0..*" Observacion : registra
Observacion "*" -- "1" Especie : corresponde a
Observacion "*" -- "1" Lugar : ocurre en
Observacion "1" -- "0..*" Fotografia : contiene

@enduml